# SwiftLint Configuration for Kipple

# Included and excluded paths
included:
  - Kipple
  - KippleTests

excluded:
  - build
  - DerivedData
  - .build
  - Package.swift
  - Kipple.xcodeproj
  - Kipple/Assets.xcassets
  - Kipple/Preview Content

# Rules configuration
disabled_rules:
  - trailing_whitespace # Handled by editor
  - todo # Allow TODO comments during development
  - file_header # Disable file header requirement for now
  - vertical_whitespace_opening_braces # Allow spacing after opening braces

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

# Rule customization
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 3
    error: 6

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - URL
    - UI
    - CGEvent
    - ax
    - x
    - y

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 60

# Custom rules for the project
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use logging instead of print statements"
    severity: warning
  
  no_nslog:
    name: "No NSLog"
    regex: '\bNSLog\s*\('
    message: "Use os_log instead of NSLog"
    severity: warning
  
# Reporter configuration
reporter: "xcode"

# Warning threshold
warning_threshold: 100

# Analyzer rules
analyzer_rules:
  - explicit_self